### ISSUE TITLE
Download the psd file from the webui server to local.

### ISSUE THREAD

**Issue by Changesong** [jhj0517/stable-diffusion-webui-Layer-Divider#13]
Hi, thanks for the awesome plugin.

I'm currently using webui on a server. And this is a great plugin! But if you don't mind, I'd like to talk about a problem I'm having.
Since the created psd file is stored on the server and there is no way to download to client on webui, it is inconvenient to move it from the server every time. Images can be downloaded with a right-click in the webui, which is much easier.

I wish there was a way to save the psd files on client side.
Could you please implement this feature? thank you.

**Comment by jhj0517** [comment]
Closing since this has been merged at #15
