### ISSUE TITLE
Extension installed but no tab appearing

### ISSUE THREAD

**Issue by 0m3ga4** [jhj0517/stable-diffusion-webui-Layer-Divider#3]
[Screenshot on Imgur](https://imgur.com/a/LQtxVH7)

**Comment by 0m3ga4** [comment]
Yeah it's a fresh boot on an updated webui. Is it possible that it might conflict with another extension? I do have quite a few tabs from them. 
Sorry in advance if that's a silly suggestion, I'm not sure how that all works internally.

**Comment by jhj0517** [comment]
If the tab was not added properly, there might be some logs in the cmd. 
Could you provide the logs from the cmd when you launched SD WebUI?

**Comment by 0m3ga4** [comment]
`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading A111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Settings file found, loading
 →   Updating Settings File  ✓
 i   Launcher Version 1.7.0
 i   Found a custom WebUI Config
 i   No Launcher launch options
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Checking requirements :
 i   Python 3.10.6150.1013 found in registry:  C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\
 i   Clearing PATH of any mention of Python
 →   Adding python 3.10 to path  ✓
 i   Git found and already in PATH:  C:\Program Files\Git\cmd\git.exe
 i   Automatic1111 SD WebUI found:  C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui
 i   One or more checkpoint models were found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading Complete, opening launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --medvram --xformers --no-half-vae
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Webui
 ✓   Done
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: a1111-sd-webui-locon
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: loopback_scaler
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: multidiffusion-upscaler-for-automatic1111
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: openpose-editor
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd-webui-3d-open-pose-editor
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd-webui-aspect-ratio-helper
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd-webui-controlnet
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd-webui-cutoff
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd-webui-multiple-hypernetworks
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd-webui-regional-prompter
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd_civitai_extension
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: Stable-Diffusion-Webui-Civitai-Helper
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: stable-diffusion-webui-composable-lora
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: stable-diffusion-webui-Layer-Divider
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: stable-diffusion-webui-pixelization
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: stable-diffusion-webui-state
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: stable-diffusion-webui-text2prompt
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: stable-diffusion-webui-two-shot
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: ultimate-upscale-for-automatic1111
 ✓   Done
 i   Arguments are now: --medvram --xformers --no-half-vae
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
venv "C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI



#######################################################################################################
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Civitai Link revision: c4d4b2e374eccb5f192929a1332e46852f494173
SD-WebUI revision: 22bcc7be428c94e9408f589966c2040187245d81

Checking Civitai Link requirements...
[!] python-socketio[client] version 5.7.2 NOT installed.

#######################################################################################################


Launching Web UI with arguments: --autolaunch --medvram --xformers --no-half-vae
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Hypernetwork-MonkeyPatch-Extension not found
Civitai: API loaded
Installing Layer Divider Extension: Installing  segment-anything
Installing Layer Divider Extension: Installing  opencv-python
Installing Layer Divider Extension: Installing  pycocotools
Error loading script: layer_divider.py
Traceback (most recent call last):
  File "C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\extensions\stable-diffusion-webui-Layer-Divider\scripts\layer_divider.py", line 2, in <module>
    install_sam()
  File "C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\extensions\stable-diffusion-webui-Layer-Divider\scripts\layer_divider_modules\installation.py", line 13, in install_sam
    run_pip(
  File "C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\launch.py", line 129, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Layer Divider Extension: Installing  pycocotools.
Command: "C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install pycocotools --prefer-binary
Error code: 1
stdout: Collecting pycocotools
  Using cached pycocotools-2.0.6.tar.gz (24 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy in c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages (from pycocotools) (1.23.3)
Requirement already satisfied: matplotlib>=2.1.0 in c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages (from pycocotools) (3.7.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (9.4.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (2.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (23.0)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (0.11.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (1.0.7)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (4.39.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.1.0->pycocotools) (1.16.0)
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (pyproject.toml): started
  Building wheel for pycocotools (pyproject.toml): finished with status 'error'
Failed to build pycocotools

stderr: WARNING: Ignoring invalid distribution -rotobuf (c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages)
  error: subprocess-exited-with-error

  Building wheel for pycocotools (pyproject.toml) did not run successfully.
  exit code: 1

  [16 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-310\pycocotools
  running build_ext
  cythoning pycocotools/_mask.pyx to pycocotools\_mask.c
  C:\Users\ADMIN\AppData\Local\Temp\pip-build-env-bg2qb7f8\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\ADMIN\AppData\Local\Temp\pip-install-wx6gy12n\pycocotools_e70609cdcc9c402c972ee54acde5b6ad\pycocotools\_mask.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'pycocotools._mask' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects
WARNING: Ignoring invalid distribution -rotobuf (c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\admin\documents\ai's\stable-diffusion-webui\venv\lib\site-packages)

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip



[text2prompt] Following databases are available:
    all-mpnet-base-v2 : danbooru_strict
Loading weights [71b0af99df] from C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\models\Stable-diffusion\soapmix25D_v10.safetensors
Creating model from config: C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\Users\ADMIN\Documents\AI's\stable-diffusion-webui\models\VAE\kl-f8-anime2.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Textual inversion embeddings skipped(3): nartfixer, nfixer, nrealfixer
Model loaded in 6.0s (load weights from disk: 0.3s, create model: 0.3s, apply weights to model: 4.1s, apply half(): 0.6s, load VAE: 0.6s).
[text2prompt] Loading database with name "all-mpnet-base-v2 : danbooru_strict"...
[text2prompt] Database loaded
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Civitai: Check resources for missing preview images
Startup time: 33.2s (import torch: 4.1s, import gradio: 0.7s, import ldm: 0.6s, other imports: 0.9s, load scripts: 16.4s, load SD checkpoint: 6.3s, create ui: 2.7s, gradio launch: 0.2s, scripts app_started_callback: 1.2s).
Civitai: Found 12 resources missing preview images
Civitai Helper: Start load_lora_configs
Civitai Helper: Send lora config to js
Civitai Helper: Start build_msg
Civitai Helper: End build_msg
Civitai Helper: End load_lora_configs
Civitai: Found 2 hash matches
Civitai: Updated 0 preview images
`

There is an error coming from layer divider by the looks of it. Telling me I'm missing C++ build tools, although it seems a bit strange that it's the only plugin to have that issue. I'll install it and let you know if that solves the problem.

**Comment by 0m3ga4** [comment]
So, I already had it installed but reinstalling it did not solve the problem. At this point I'm not sure what to do.

**Comment by tarunabhdutta** [comment]
Same problem here: Error loading script: layer_divider.py
Traceback (most recent call last):
  File "C:\SD\stable-diffusion-webui-master\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\SD\stable-diffusion-webui-master\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SD\stable-diffusion-webui-master\extensions\stable-diffusion-webui-Layer-Divider\scripts\layer_divider.py", line 1, in <module>
    from scripts.layer_divider_modules.installation import *
ModuleNotFoundError: No module named 'scripts.layer_divider_modules'

**Comment by brehiner** [comment]
Same error:

Error loading script: layer_divider.py
Traceback (most recent call last):
  File "C:\Users\Hello\Documents\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Hello\Documents\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module

**Comment by Markjinli** [comment]
哭了，我也显示不出来，但是我下载单独的[layerdivider](https://github.com/mattyamonaca/layerdivider)是可以用的

**Comment by jhj0517** [comment]
Fixed requirements in #26. 
If anyone still face the error, please re-open.
