### ISSUE TITLE
I can't see the layer-divider tab even though I've restarted the webui. Why is this? Is it because of the kernel version?

### ISSUE THREAD

**Issue by Kevin-chan0514** [jhj0517/stable-diffusion-webui-Layer-Divider#30]
hello ! I can't see the layer-divider tab even though I've restarted the webui. Why is this? Is it because of the kernel version?

**Comment by Kevin-chan0514** [comment]
Can't you see the layer divider tab when you run it with the latest version?


「jhj0517 ***@***.***>」在 2024年8月7日 週三，20:17 寫道：

**Comment by jhj0517** [comment]
@Kevin-chan0514. The tab should normally appear on the latest version of the web ui.
If you still have a problem, try reinstalling some packages. See [Notice](https://github.com/jhj0517/stable-diffusion-webui-Layer-Divider?tab=readme-ov-file#notice--read-if-you-face-an-error-during-installation-) about it. 

And to reproduce the error, you should paste your error log.

**Comment by Kevin-chan0514** [comment]
[image: image.png]
I was careless and I got this error in the console. What could be the
reason? Can you share it? I would be grateful. Haha, I think I saw your
share on reddit too.


jhj0517 ***@***.***> 于2024年8月7日周三 21:20写道：

**Comment by jhj0517** [comment]
Your image is not displayed, can you have a conversation in
https://github.com/jhj0517/stable-diffusion-webui-Layer-Divider/issues/30 
instead of gmail?

Usually the most problematic package is a pytoshop and you can fix it by manually reinstalling the packages, as the README says.

1. Open the terminal in the WebUI and activate the venv
```
C:\YourPath\To_SD_WebUI>venv\Scripts\activate
```
2. Then it will display (venv) in front of the terminal like this.
```
(venv) C:\YourPath\To_SD_WebUI>
```
3. In this state, run
```
pip uninstall -y pytoshop
pip uninstall -y packbits
pip install git+https://github.com/jhj0517/forked-pytoshop.git
pip install packbits
```

**Comment by Kevin-chan0514** [comment]
hello i got a issue 。[image: 1723114887654.jpg]
Do I need to install C++?

jhj0517 ***@***.***> 于2024年8月7日周三 23:05写道：

**Comment by Kevin-chan0514** [comment]
success....ty very much ! ! !

Jianfeng Chen ***@***.***> 于2024年8月8日周四 19:03写道：
